server:
  servlet:
    context-path: /

# 单节点配置
spring:
  profiles:
    active: node1
  # 做服务发现是使用（必须唯一）
  application:
    name: jiiiiiin-product
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
      probability: 1.0
  zipkin:
    # 指定了 Zipkin 服务器的地址
    base-url: http://jiiiiiin-zipkin:9411/
  boot:
    admin:
      client:
        url: http://jiiiiiin-springboot-admin:5000
eureka:
#    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    service-url:
      # 指定服务注册中心的地址
      defaultZone: http://localhost:8761/eureka/
    # 服务提供方需要注册到eureka-server
    # 如果是需要被zuul调用也需要注册
    register-with-eureka: true
    # 需要获取其他服务提供方，故需要拉取配置信息
    fetch-registry: true

feign:
  hystrix:
    # Feign是自带断路器的，在D版本的Spring Cloud之后，它没有默认打开。需要在配置文件中配置打开它，在配置文件加以下代码
    enabled: true
management:
  endpoint:
    web:
      exposure:
        include: '*'
---
# 多节点配置

spring:
  profiles: node1
server:
  port: 7000

---

spring:
  profiles: node2
server:
  port: 7001

